<?php

namespace Database\Seeders;

use App\Models\Cargo;
use App\Models\Examen;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Date;
class ExamenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3757')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3757', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3912')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3912', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3957')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3957', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4003')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4003', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4006')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4006', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4222')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4222', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4000')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4000', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3101')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3101', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4220')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4220', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4217')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4217', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4225')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4225', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '2980')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 2980', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4218')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4218', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4215')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4215', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '2971')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 2971', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4216')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4216', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4226')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4226', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4221')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4221', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4227')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4227', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4228')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4228', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4229')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4229', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4211')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4211', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4219')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4219', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '2997')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 2997', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3005')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3005', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3055')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3055', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '2994')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 2994', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3027')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3027', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4186')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4186', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3934')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3934', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3987')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3987', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3990')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3990', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3991')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3991', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3995')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3995', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3011')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3011', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4233')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4233', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4209')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4209', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4200')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4200', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4202')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4202', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4194')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4194', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4210')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4210', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4203')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4203', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4199')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4199', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4208')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4208', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4195')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4195', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4196')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4196', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4204')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4204', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4197')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4197', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4198')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4198', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4201')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4201', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4207')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4207', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4206')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4206', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4205')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4205', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3051')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3051', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '2991')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 2991', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4212')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4212', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4234')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4234', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4223')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4223', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4224')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4224', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '3961')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 3961', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4232')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4232', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4213')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4213', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);
        Examen::firstOrCreate([ 'cargo_id' => Cargo::where('codigo', '4214')->value('id'), 'titulo' => 'EXAMEN DE CONOCIMIENTO - 4214', 'fecha' => date('Y-m-d'), 'hora_inicio' => date('H:i:s', strtotime('08:09:00')), 'hora_fin' => date('H:i:s', strtotime('12:00:00')), 'duracion' => 20 ]);


    }
}
